// string type variable
var bottle = 'water';
var bottleColor = 'yellow';
// number type variable
var bottlePrice = 120;
var salary = 15000;
// boolean type variable
var isExpensive = true;
var notExpensive = false;